# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        none

# Setup
title:            code.Antrikshy
tagline:          'Notes, tinkerings, experiments'
url:              http://code.antrikshy.com
paginate:         3
paginate_path:    "/blog/page:num"
excerpt_separator: "<!--more-->"
baseurl:          /
highlighter:      pygments
author:
  name:           Antriksh Yadav
  url:            https://antrikshy.com
  email:          antrikshy@gmail.com

# Custom vars
github:
  repo:           https://github.com/Antrikshy/antrikshy.github.io
pages_list:       
  Entries:        '/entries.html'
  Feed:           '/atom.xml'
  Blog:           '/blog'